create table tb_notas (id int8 generated by default as identity, descricao varchar(255), titulo varchar(255), primary key (id));

INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota luz','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota agua','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota telefone','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota celular','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota cadeira scritório','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota compras mercado','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota compras de roupa','Pagamento do mês 08/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota luz','Pagamento do mês 07/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota agua','Pagamento do mês 07/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota telefone','Pagamento do mês 07/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota celular','Pagamento do mês 07/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota almoço','Pagamento do mês 07/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota luz','Pagamento do mês 06/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota agua','Pagamento do mês 06/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota telefone','Pagamento do mês 06/2021');
INSERT INTO tb_sales(titulo,descricao) VALUES ('Nota celular','Pagamento do mês 06/2021');
